disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "gebt1000's blog"
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
copyright = "&copy; gebt1000"

[params.author]
name = "gebt1000"
# image = "img/pfp.jpeg"
imageQuality = 96
headline = " "
bio = "A little bit about you"

  [[params.author.links]]
  instagram = "https://www.instagram.com/gebt1000"

  [[params.author.links]]
  spotify = "https://open.spotify.com/user/31ueqcem7pqdylxp72xfpxuxzkyy?si=b3293b1fbd024c0b"

["params.author"]
image = "pfp.jpeg"
imageQuality = "96"
headline = " "
